### PR TITLE
[WIP] Switch to using python-libzim from zimwriterfs

### PR DESCRIPTION
**Pull request by pirate**

### CODE REVIEW

**Comment by jdcaballerov** [comment]
This is Sotoki's architecture without integration:

Screen Shot 2020-04-27 at 07 22 32

Three (3) so called renderers (Users, Questions, Tags), that actually parse, render, do SQL, write redirects, write images, are executed sequentially.

Just the first two of them use multiprocessing.

The main python process starts filling a "local to the renderer" Queue that has (cores*2) slots.

From this "local" Queue the workers get their workload and start writing to the filesystem. Each renderer joins before continuing to execute the next renderer.

The last renderer (TAGS) doesn't use multiprocessing at all.

This is a challenge since our writing object (ZimCreator) needs to be passed deep into this functions. When ZimCreator calls finalize (where the actual writes happen, since we don't copy) all the processes and backing content were already killed.

What I did (to make it work, not because it's clean or elegant). I setted up a queue that can be shared between processes (so called managed Queue in python's lingo) and put the tasks composed of content (not article objects). Something like this:

Screen Shot 2020-04-27 at 07 21 42

So there is a parallel unique process that adds the articles (adding articles is lightweight). And every "Parser" puts it's rendered content there.

In future developments a cleaner architecture is recommended as following:

Screen Shot 2020-04-27 at 07 21 20

Parsers should only parse and yield or return items.

**Comment by jdcaballerov** [comment]
**How the integration proceeded**

A Managed Queue is declared at `run()`

```python
zim_write_manager = Manager()
zim_write_queue = zim_write_manager.Queue()
```

A unique listener is initialized to receive `add_article` events 

```python
zim_file_metadata = {'creator': scraper_version,
                            'description': description,
                            'name': domain, 
                            'publisher': publisher,
                            'title': title }

# Zim Creator Conf
ZimFileConf = collections.namedtuple('ZimFileConf',['path', 'main_page', 'index_language','metadata'])
zim_file_conf = ZimFileConf(path=zim_file_path, main_page='index.html', 
                                    index_language=languageToAlpha3(lang_input),
                                    metadata=zim_file_metadata)
# Start a unique listener process to add articles
zim_watcher = Process(target=zim_write_listener, args=(zim_write_queue, zim_file_conf,))
zim_watcher.start()
```
The listener obtains articles to add according to the requirements.

```python
def zim_write_listener(q, zim_file_conf):
    zim_creator = zim_creator_init(zim_file_conf.path, 
                                zim_file_conf.main_page, 
                                zim_file_conf.index_language)
    while True:
        item = q.get()
        if item is None:
            zim_creator.update_metadata(**zim_file_conf.metadata) 
            zim_creator.finalize()     
            break
        else:
            article = get_article_for_action(item)
            zim_creator.add_article(article)
```

The article dispatcher constructs the appropriate article according to the event. Article types are declared at `article.py` and can be extended.

```python
def get_article_for_action(item):
    action, *args = item
    if action == "add_content_article":
        url, title, content = args
        article = ContentArticle(url= url,
                             title= title, 
                             content=content)
    elif action == "add_redirect_article":
        ns, url, redirect_url, title = args
        article = RedirectArticle(f"{ns}/{url}", redirect_url, title)

    elif action == "add_static_article":
        ns, fullpath, content = args 
        # Set the title as the filename+ext
        url = get_url_from_file_full_path(fullpath)
        title = url.split('/')[-1:][0]
        # TODO use magic for files without extension
        mimetype = get_mime_from_extension(title.split('.')[-1:][0])
        article = StaticAssetArticle(ns, url, title, mimetype, content)
```

**Comment by jdcaballerov** [comment]
**How to use**

To add articles the caller must have access to the shared queue and put tasks in that queue corresponding to declared events at the dispatcher with all the required parameters.

For example the former `jinja` function adds content articles as follows:

```python
def jinja(output, template, templates, raw, deflate, zim_write_queue, **context):
    template = ENV.get_template(template)
    page = template.render(**context)
    if raw:
        page = "{% raw %}" + page + "{% endraw %}"
    if deflate:
        title = get_title_from_render_context(template, context)
        url = get_url_from_file_full_path(output)

        # Add article data to queue
        data = ('add_content_article', url, title, page.encode('UTF-8'))
        zim_write_queue.put(data)
```
Similarly images (calling from all the places where images were written) or redirects (by sequentially reading the file) are added

```python
# IMAGES
#Called in download_image or someuser for identicon
zim_write_queue.put(('add_static_article', 'I', fullpath, content,))

# REDIRECTS
data = ('add_redirect_article', ns, url, redirect_url, title,)
zim_write_queue.put(data)
```

**Comment by jdcaballerov** [comment]
**What works ?**

- All content articles are added with multiprocessing (Users, Questions, Tags with alltags, index, etc)
- All redirects articles are added from the generated CSV file 
- The navigation works and links are correct.
- Images are written (no kiwix-storage) but need to check if contents are ok due to use of NamedTempFiles, also need to check url since templates use the variable `rooturl`

** What's left to do**

- Finish WIP for images (need to verify contents and paths)
-  Support the `kiwix-storage` cache for images. 
- Check if zim file `name` metadata is ok.
-  Add recusively static assets different to the added files
-  AdaptCSS and links as it's done in `zimwritefs` to ensure all static are correct

**Comment by jdcaballerov** [comment]
Easy path to url debug (for static, images and others)
------------------------------------------------------

Using the `ZimFileReader` from `reader` branch let's debug the images:

```python3
from libzim import ZimFileReader

reader = ZimFileReader('./work/tezos.stackexchange.com_en_all_2020-04.zim'

identicon = reader.get_article('I/static/identicon/2428.png')
user = reader.get_article('A/user/2428.html')

user.content
```

Shows how image is written in the Content Article
``
So you need to pass the `fullpath` in `some_user()` that goes into 
`zim_write_queue.put(('add_static_article', 'I', fullpath, identicon, ))`
filtering the `../` and all identicons will work.

For images is similar, you need to correct `image()` and change this line `src = "..   /static/images/" + filename` to have one dot only.

I guess with this simple steps images will work. Need to check since code modifies many things in many places and it's not ordered.

**Comment by kelson42** [comment]
The usage of python-libzim will happen through the zimscraperlib. Discontinued,

**Pull request closed without merging**
