### PR TITLE
Fix mistune bug and harmonize versioning

### LINKED ISSUE #108: Error with mistune
Apparently, sometime mistune, which do markdown to html crash.
We should investigate and fix this issue.

Step to reproduice :
```
sotoki wordpress.stackexchange.com Kiwix --threads=1 --reset --clean-previous --no-userprofile --nopic --nozim
```

```
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/bin/sotoki", line 11, in <module>
    load_entry_point('sotoki==1.2', 'console_scripts', 'sotoki')()
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/sotoki-1.2-py3.7.egg/sotoki/sotoki.py", line 1530, in run
    parser.parse(os.path.join(dump, "prepare.xml"))
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.7/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "../Modules/pyexpat.c", line 417, in StartElement
  File "/usr/lib/python3.7/xml/sax/expatreader.py", line 333, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/sotoki-1.2-py3.7.egg/sotoki/sotoki.py", line 199, in startElement
    tmp["Text"] = markdown(html.escape(tmp["Text"], quote=False))
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/sotoki-1.2-py3.7.egg/sotoki/sotoki.py", line 767, in markdown
    text_html = MARKDOWN(text)[3:-5]
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/mistune-2.0.0a2-py3.7.egg/mistune/markdown.py", line 69, in __call__
    return self.parse(s)
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/mistune-2.0.0a2-py3.7.egg/mistune/markdown.py", line 54, in parse
    result = self.block.render(tokens, self.inline, state)
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/mistune-2.0.0a2-py3.7.egg/mistune/block_parser.py", line 246, in render
    return ''.join(data)
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/mistune-2.0.0a2-py3.7.egg/mistune/block_parser.py", line 263, in _iter_render
    yield method(children, *params)
  File "/home/dattaz/dev/kiwix/sotoki/sotoki/venv3/lib/python3.7/site-packages/mistune-2.0.0a2-py3.7.egg/mistune/renderers.py", line 175, in block_code
    lang = info.strip().split(None, 1)[0]
IndexError: list index out of range
```

### LINKED ISSUE #112: $sotoki --version is wrong
```
$ sudo -H pip3 install sotoki
Collecting sotoki
  Downloading https://files.pythonhosted.org/packages/63/d5/d31b529aa6606de53a503ad95ce791fefe80673f706e8d3fe23881377096/sotoki-1.2-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 989kB/s 
Collecting Jinja2==2.11.1 (from sotoki)
  Downloading https://files.pythonhosted.org/packages/27/24/4f35961e5c669e96f6559760042a55b9bcfcdb82b9bdb3c8753dbe042e35/Jinja2-2.11.1-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 3.6MB/s 
Collecting mistune>=2.0.0a2 (from sotoki)
  Downloading https://files.pythonhosted.org/packages/0d/11/984bef066f571c72607f41dedf77a5404e7870eeb812658b34fc085d892a/mistune-2.0.0a2-py2.py3-none-any.whl
Requirement already satisfied: Pillow==7.0.0 in /usr/local/lib/python3.6/dist-packages (from sotoki)
Collecting python-slugify==4.0.0 (from sotoki)
  Downloading https://files.pythonhosted.org/packages/92/5f/7b84a0bba8a0fdd50c046f8b57dcf179dc16237ad33446079b7c484de04c/python-slugify-4.0.0.tar.gz
Requirement already satisfied: MarkupSafe==1.1.1 in /usr/local/lib/python3.6/dist-packages (from sotoki)
Collecting filemagic==1.6 (from sotoki)
  Using cached https://files.pythonhosted.org/packages/8f/67/a1aedccc143597eea90e79134d14c7364e90174d31443e14674919716d87/filemagic-1.6.tar.gz
Collecting beautifulsoup4==4.8.2 (from sotoki)
  Downloading https://files.pythonhosted.org/packages/cb/a1/c698cf319e9cfed6b17376281bd0efc6bfc8465698f54170ef60a485ab5d/beautifulsoup4-4.8.2-py3-none-any.whl (106kB)
    100% |████████████████████████████████| 112kB 4.6MB/s 
Collecting lxml==4.5.0 (from sotoki)
  Downloading https://files.pythonhosted.org/packages/dd/ba/a0e6866057fc0bbd17192925c1d63a3b85cf522965de9bc02364d08e5b84/lxml-4.5.0-cp36-cp36m-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.8MB 327kB/s 
Collecting pydenticon==0.3.1 (from sotoki)
  Downloading https://files.pythonhosted.org/packages/76/fa/3085252e2cfd8353624142fb18ca007a2ce4fe199a1440ea3c85ec5b8620/pydenticon-0.3.1.tar.gz
Requirement already satisfied: docopt==0.6.2 in /usr/local/lib/python3.6/dist-packages (from sotoki)
Collecting text-unidecode>=1.3 (from python-slugify==4.0.0->sotoki)
  Downloading https://files.pythonhosted.org/packages/a6/a5/c0b6468d3824fe3fde30dbb5e1f687b291608f9473681bbf7dabbf5a87d7/text_unidecode-1.3-py2.py3-none-any.whl (78kB)
    100% |████████████████████████████████| 81kB 6.4MB/s 
Collecting soupsieve>=1.2 (from beautifulsoup4==4.8.2->sotoki)
  Downloading https://files.pythonhosted.org/packages/05/cf/ea245e52f55823f19992447b008bcbb7f78efc5960d77f6c34b5b45b36dd/soupsieve-2.0-py2.py3-none-any.whl
Building wheels for collected packages: python-slugify, filemagic, pydenticon
  Running setup.py bdist_wheel for python-slugify ... done
  Stored in directory: /root/.cache/pip/wheels/11/94/81/312969455540cb0e6a773e5d68a73c14128bfdfd4a7969bb4f
  Running setup.py bdist_wheel for filemagic ... done
  Stored in directory: /root/.cache/pip/wheels/2e/0e/8e/c4625de9d6f723017996dd718d5fabe1c7bb1fbce7389d3bf6
  Running setup.py bdist_wheel for pydenticon ... done
  Stored in directory: /root/.cache/pip/wheels/76/ca/72/96647e22a377a57300fabf9739df964db7466c926be27f4934
Successfully built python-slugify filemagic pydenticon
Installing collected packages: Jinja2, mistune, text-unidecode, python-slugify, filemagic, soupsieve, beautifulsoup4, lxml, pydenticon, sotoki
  Found existing installation: Jinja2 2.10.1
    Uninstalling Jinja2-2.10.1:
      Successfully uninstalled Jinja2-2.10.1
  Found existing installation: text-unidecode 1.2
    Uninstalling text-unidecode-1.2:
      Successfully uninstalled text-unidecode-1.2
  Found existing installation: python-slugify 3.0.3
    Uninstalling python-slugify-3.0.3:
      Successfully uninstalled python-slugify-3.0.3
  Found existing installation: beautifulsoup4 4.6.0
    Not uninstalling beautifulsoup4 at /usr/lib/python3/dist-packages, outside environment /usr
  Found existing installation: lxml 4.2.1
    Not uninstalling lxml at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed Jinja2-2.11.1 beautifulsoup4-4.8.2 filemagic-1.6 lxml-4.5.0 mistune-2.0.0a2 pydenticon-0.3.1 python-slugify-4.0.0 sotoki-1.2 soupsieve-2.0 text-unidecode-1.3
kelson@camber:/dev/shm/sotoki$ sotoki --version
sotoki 1.0
```

`pip` says it installs `sotoki-1.2` but the version printed is `1.0`.

### PR DESCRIPTION
**Pull request by satyamtg**
Fixes #108 
Fixes #112 

This PR fixes the mistune bug until a permanent solution is provided by mistune devs. Also, it harmonizes the versioning and makes use of importlib.metadata to determine version at runtime in sotoki.py

### CODE REVIEW

**Comment by kelson42** [comment]
@satyamtg Thank you for your patch. In the future try to make one PR per ticket to fix (except of course if this is the real same problem) and try to split your work in multiple clear/small commits.

**Comment by satyamtg** [comment]
@kelson42 I just received a response on the issue I created with mistune. They just released a new version and say that it's fixed in that. I'll check and update this PR for the same. Hopefully we don't need to strip spaces ourselves now.

**Comment by kelson42** [comment]
@satyamtg If you make a commit where you upgrade to latest version all the deps, I believe this would be welcome.

**Comment by satyamtg** [comment]
@kelson42, have checked and removed the trailing space stripping code. Also updated the dependencies to their latest versions.

**Comment by rgaudin** [comment]
Thanks @satyamtg but I'd also prefer separate PRs.

* multiple fixes in single PR is hard to review which means it will gets postponed.
* don't just bump dependencies version ; and don't bundle it with other stuff. I know @kelson42 asked for this but still, this should be separate and thorough-fully tested. 
* please specify ways to check what you fixed. For mistune, provide a zim + URL for which  it was failing and for which it now works so I can verify.

Also, what you propose for the version is not OK

``` sh
python sotoki/sotoki.py --version
Traceback (most recent call last):
  File "sotoki/sotoki.py", line 1596, in <module>
    run()
  File "sotoki/sotoki.py", line 1330, in run
    scraper_version = "sotoki " + metadata.version("sotoki")
  File "/Users/reg/src/envs/sotoki/lib/python3.8/importlib/metadata.py", line 472, in version
    return distribution(distribution_name).version
  File "/Users/reg/src/envs/sotoki/lib/python3.8/importlib/metadata.py", line 445, in distribution
    return Distribution.from_name(distribution_name)
  File "/Users/reg/src/envs/sotoki/lib/python3.8/importlib/metadata.py", line 169, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: sotoki
```

It works only on installed versions… All our scrapers have a `--version` tag so look at what we've done there instead.

Last advise, I find it cleaner to have the issue number in the PR title (like `Fixed #108: bumped mistune dep version`). This way, it goes into the merge commit and the git log is more useful (can be edited in the PR or when merging though so that's not much of a deal).

**Comment by satyamtg** [comment]
> Thanks @satyamtg but I'd also prefer separate PRs.
> 
> * multiple fixes in single PR is hard to review which means it will gets postponed.
> * don't just bump dependencies version ; and don't bundle it with other stuff. I know @kelson42 asked for this but still, this should be separate and thorough-fully tested.
> * please specify ways to check what you fixed. For mistune, provide a zim + URL for which  it was failing and for which it now works so I can verify.
> 
> Also, what you propose for the version is not OK
> 
> ```shell
> python sotoki/sotoki.py --version
> Traceback (most recent call last):
>   File "sotoki/sotoki.py", line 1596, in <module>
>     run()
>   File "sotoki/sotoki.py", line 1330, in run
>     scraper_version = "sotoki " + metadata.version("sotoki")
>   File "/Users/reg/src/envs/sotoki/lib/python3.8/importlib/metadata.py", line 472, in version
>     return distribution(distribution_name).version
>   File "/Users/reg/src/envs/sotoki/lib/python3.8/importlib/metadata.py", line 445, in distribution
>     return Distribution.from_name(distribution_name)
>   File "/Users/reg/src/envs/sotoki/lib/python3.8/importlib/metadata.py", line 169, in from_name
>     raise PackageNotFoundError(name)
> importlib.metadata.PackageNotFoundError: sotoki
> ```
> 
> It works only on installed versions… All our scrapers have a `--version` tag so look at what we've done there instead.
> 
> Last advise, I find it cleaner to have the issue number in the PR title (like `Fixed #108: bumped mistune dep version`). This way, it goes into the merge commit and the git log is more useful (can be edited in the PR or when merging though so that's not much of a deal).

@rgaudin , thanks for your advice. It will surely help in getting things done faster and better community understanding. Will create separate PRs.

**Pull request closed without merging**
