### PR TITLE
Option : specify a censor list of word to remplace with XXX

### LINKED ISSUE #187: Option to censor forbidden words
Based on a list.

### PR DESCRIPTION
**Pull request by dattaz**
Fix #187

### CODE REVIEW

**Comment by dattaz** [comment]
Note : this is a really naive but simple implementation

**Review by rgaudin — CHANGES_REQUESTED** [review]
Thanks @dattaz 

While it's naive, I think it does what is required efficiently. The google bad word list is under 500 words anyway.

What I think we need though is the ability to receive a URL as parameter instead of a path (it should accept both) because that's how it's gonna be used inside the container.

**Comment by rgaudin** [comment]
@dattaz, you force-pushed a commit but I don't see the difference (there's no url support). Should it be reviewed again?

**Comment by dattaz** [comment]
No it was a mistake. I'll take a look to add url support this week end

**Comment by kelson42** [comment]
@dattaz Any update?

**Comment by rgaudin** [comment]
Obsolete, can't be merged. @kelson42 why reviving those old PRs ?

**Comment by kelson42** [comment]
As long as the PR makes progress and in syn with reality, then good for me.

**Comment by rgaudin** [comment]
As you know, master has changed and the old file paths are not present anymore so no old PR can be merged.

**Comment by kelson42** [comment]
Yes, but PRs can updates, fixed, etc. I'm fine as well with the "closing scenario".

**Comment by rgaudin** [comment]
😳

**Pull request closed without merging**
