### PR TITLE
To python3

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by kelson42** [comment]
@dattaz I have open a draft PR. I will just check if it runs. That saids, CodeFactor reports quite a few oddities.

**Comment by kelson42** [comment]
@dattaz Does not run at all for me.
```
$ sotoki
Traceback (most recent call last):
  File "/home/kelson/code/sotoki/bin/sotoki", line 5, in <module>
    from sotoki.sotoki import run
  File "/home/kelson/code/sotoki/lib/python3.6/site-packages/sotoki/__init__.py", line 1, in <module>
    from sotoki import run
ImportError: cannot import name 'run'
```

**Comment by rgaudin** [comment]
I know it's still a draft PR but tried it anyway…

```
Extracting archive: ukrainian.stackexchange.com.7z
--
Path = ukrainian.stackexchange.com.7z
Type = 7z
Physical Size = 6128601
Headers Size = 306
Method = BZip2
Solid = +
Blocks = 1

Everything is Ok

Files: 8
Size:       40536287
Compressed: 6128601
found
Ok we have get dump
Traceback (most recent call last):
  File "/usr/local/bin/sotoki", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/sotoki/sotoki.py", line 1098, in run
    renderer = mistune.HTMLRenderer()
AttributeError: module 'mistune' has no attribute 'HTMLRenderer'
```

**Comment by dattaz** [comment]
Oups mistune seems to have a new rewrite, with API break. As it seems their new version is working well, I have fix version in `setup.py` by taking their v2 release.

Anyway, so far, from what I've tried with python3 port of sotoki, it seems to work to docker file :) except issue #95

**Comment by rgaudin** [comment]
@dattaz can we move forward with this? It's still in draft state…

**Comment by rgaudin** [comment]
@dattaz not sure why you added `--source` in zimwriterfs (3ecd089599184b08858d8d5657c68d8e62bc1081) but it's not valid in current zimwriterfs. I couldn't find any older version with it so I just removed it.

**Comment by kelson42** [comment]
> @dattaz not sure why you added `--source` in zimwriterfs ([3ecd089](https://github.com/openzim/sotoki/commit/3ecd089599184b08858d8d5657c68d8e62bc1081)) but it's not valid in current zimwriterfs. I couldn't find any older version with it so I just removed it.

We have finally dediced to implement the option in `zimwriterfs`, but `https://` must be added properly to the hostname value. This should be fixed.

**Comment by rgaudin** [comment]
it's already back…

**Pull request merged**
